;; -*- mode: eask; lexical-binding: t -*-

(package "lsp-ellsp"
         "0.2.0"
         "LSP Clients for Ellsp")

(website-url "https://github.com/elisp-lsp/lsp-ellsp")
(keywords "convenience")

(package-file "lsp-ellsp.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "28.1")
(depends-on "lsp-mode")

(development
 (depends-on "ellsp"))
